/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grading_Calculator;

import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alex
 */
public class GradingCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GradingCalculator
     */
    public GradingCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        calculateBtn = new javax.swing.JButton();
        transcriptBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        gradingPanel = new javax.swing.JPanel();
        gradesLbl = new javax.swing.JLabel();
        stuIdLbl = new javax.swing.JLabel();
        lnameLbl = new javax.swing.JLabel();
        fnameLbl = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        courseIdBx = new javax.swing.JComboBox<>();
        fnameTxtBx = new javax.swing.JTextField();
        lnameTxtBx = new javax.swing.JTextField();
        studentIdTxtBx = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ictLbl = new javax.swing.JLabel();
        mathLbl = new javax.swing.JLabel();
        physicsLbl = new javax.swing.JLabel();
        bioLbl = new javax.swing.JLabel();
        chemistryLbl = new javax.swing.JLabel();
        englishLbl = new javax.swing.JLabel();
        commerceLbl = new javax.swing.JLabel();
        literatureLbl = new javax.swing.JLabel();
        ictTxtField = new javax.swing.JTextField();
        mathTxtField = new javax.swing.JTextField();
        physicsTxtField = new javax.swing.JTextField();
        bioTxtField = new javax.swing.JTextField();
        chemTxtField = new javax.swing.JTextField();
        englishTxtField = new javax.swing.JTextField();
        commerceTxtField = new javax.swing.JTextField();
        literatureTxtField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        totalLbl = new javax.swing.JLabel();
        totalTxtBx = new javax.swing.JTextField();
        avgLbl = new javax.swing.JLabel();
        avgTxtBx = new javax.swing.JTextField();
        rankLbl = new javax.swing.JLabel();
        rankTxtBx = new javax.swing.JTextField();
        transcriptPanel = new javax.swing.JPanel();
        transcriptLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transcriptArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("grading_calculator_form");
        setBackground(new java.awt.Color(70, 83, 98));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setSize(new java.awt.Dimension(1000, 800));

        mainPanel.setBackground(new java.awt.Color(244, 255, 253));
        mainPanel.setForeground(new java.awt.Color(244, 255, 253));
        mainPanel.setAutoscrolls(true);
        mainPanel.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        mainPanel.setMinimumSize(new java.awt.Dimension(100, 600));
        mainPanel.setSize(new java.awt.Dimension(1000, 800));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(237, 37, 78));
        exitBtn.setForeground(new java.awt.Color(244, 255, 253));
        exitBtn.setText("Exit");
        exitBtn.setToolTipText("");
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        mainPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 110, 40));

        calculateBtn.setBackground(new java.awt.Color(237, 37, 78));
        calculateBtn.setForeground(new java.awt.Color(244, 255, 253));
        calculateBtn.setText("Calculate");
        calculateBtn.setToolTipText("Calculate the marks");
        calculateBtn.setFocusable(false);
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        mainPanel.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, 40));

        transcriptBtn.setBackground(new java.awt.Color(237, 37, 78));
        transcriptBtn.setForeground(new java.awt.Color(244, 255, 253));
        transcriptBtn.setText("Transcript");
        transcriptBtn.setToolTipText("Generate a transcript");
        transcriptBtn.setFocusable(false);
        transcriptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcriptBtnActionPerformed(evt);
            }
        });
        mainPanel.add(transcriptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, 40));

        resetBtn.setBackground(new java.awt.Color(237, 37, 78));
        resetBtn.setForeground(new java.awt.Color(244, 255, 253));
        resetBtn.setText("Reset");
        resetBtn.setToolTipText("Reset the entered marks");
        resetBtn.setFocusable(false);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        mainPanel.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, 40));

        gradingPanel.setBackground(new java.awt.Color(1, 148, 158));

        gradesLbl.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        gradesLbl.setForeground(new java.awt.Color(244, 255, 253));
        gradesLbl.setText("Student Details");

        stuIdLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        stuIdLbl.setForeground(new java.awt.Color(244, 255, 253));
        stuIdLbl.setText("Student ID:");

        lnameLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lnameLbl.setForeground(new java.awt.Color(244, 255, 253));
        lnameLbl.setText("Last Name:");

        fnameLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        fnameLbl.setForeground(new java.awt.Color(244, 255, 253));
        fnameLbl.setText("First Name:");

        courseLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        courseLbl.setForeground(new java.awt.Color(244, 255, 253));
        courseLbl.setText("Course ID:");

        courseIdBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        courseIdBx.setForeground(new java.awt.Color(1, 25, 54));
        courseIdBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C1001", "C2853", "C5679", "C1012", "C2030" }));

        fnameTxtBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        fnameTxtBx.setForeground(new java.awt.Color(1, 25, 54));

        lnameTxtBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lnameTxtBx.setForeground(new java.awt.Color(1, 25, 54));

        studentIdTxtBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        studentIdTxtBx.setForeground(new java.awt.Color(1, 25, 54));
        studentIdTxtBx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentIdTxtBxKeyTyped(evt);
            }
        });

        ictLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        ictLbl.setForeground(new java.awt.Color(244, 255, 253));
        ictLbl.setText("ICT :");

        mathLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        mathLbl.setForeground(new java.awt.Color(244, 255, 253));
        mathLbl.setText("Mathematics :");

        physicsLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        physicsLbl.setForeground(new java.awt.Color(244, 255, 253));
        physicsLbl.setText("Physics :");

        bioLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        bioLbl.setForeground(new java.awt.Color(244, 255, 253));
        bioLbl.setText("Biology :");

        chemistryLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        chemistryLbl.setForeground(new java.awt.Color(244, 255, 253));
        chemistryLbl.setText("Chemistry :");

        englishLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        englishLbl.setForeground(new java.awt.Color(244, 255, 253));
        englishLbl.setText("English :");

        commerceLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        commerceLbl.setForeground(new java.awt.Color(244, 255, 253));
        commerceLbl.setText("Commerce :");

        literatureLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        literatureLbl.setForeground(new java.awt.Color(244, 255, 253));
        literatureLbl.setText("Literature :");

        ictTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        ictTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ictTxtFieldKeyTyped(evt);
            }
        });

        mathTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        mathTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mathTxtFieldKeyTyped(evt);
            }
        });

        physicsTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        physicsTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                physicsTxtFieldKeyTyped(evt);
            }
        });

        bioTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        bioTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bioTxtFieldKeyTyped(evt);
            }
        });

        chemTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        chemTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chemTxtFieldKeyTyped(evt);
            }
        });

        englishTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        englishTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                englishTxtFieldKeyTyped(evt);
            }
        });

        commerceTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        commerceTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                commerceTxtFieldKeyTyped(evt);
            }
        });

        literatureTxtField.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        literatureTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                literatureTxtFieldKeyTyped(evt);
            }
        });

        totalLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(244, 255, 253));
        totalLbl.setText("Total Marks:");

        totalTxtBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        totalTxtBx.setForeground(new java.awt.Color(1, 25, 54));

        avgLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        avgLbl.setForeground(new java.awt.Color(244, 255, 253));
        avgLbl.setText("Average:");

        avgTxtBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        avgTxtBx.setForeground(new java.awt.Color(1, 25, 54));

        rankLbl.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        rankLbl.setForeground(new java.awt.Color(244, 255, 253));
        rankLbl.setText("Rank:");

        rankTxtBx.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        rankTxtBx.setForeground(new java.awt.Color(1, 25, 54));

        javax.swing.GroupLayout gradingPanelLayout = new javax.swing.GroupLayout(gradingPanel);
        gradingPanel.setLayout(gradingPanelLayout);
        gradingPanelLayout.setHorizontalGroup(
            gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradingPanelLayout.createSequentialGroup()
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(fnameLbl)
                                        .addGap(3, 3, 3)
                                        .addComponent(fnameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(stuIdLbl)
                                        .addGap(6, 6, 6)
                                        .addComponent(studentIdTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradingPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(courseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(courseIdBx, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(lnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lnameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(gradesLbl))
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(literatureLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(literatureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(commerceLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(commerceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(englishLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(englishTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(chemistryLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chemTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(bioLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(physicsLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(physicsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(mathLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addComponent(ictLbl)
                                        .addGap(97, 97, 97)
                                        .addComponent(ictTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(gradingPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addComponent(avgLbl)
                                .addGap(18, 18, 18)
                                .addComponent(avgTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addComponent(totalLbl)
                                .addGap(18, 18, 18)
                                .addComponent(totalTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addComponent(rankLbl)
                                .addGap(18, 18, 18)
                                .addComponent(rankTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        gradingPanelLayout.setVerticalGroup(
            gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradingPanelLayout.createSequentialGroup()
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradingPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(gradesLbl)
                        .addGap(18, 18, 18)
                        .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradingPanelLayout.createSequentialGroup()
                                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentIdTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stuIdLbl)
                                            .addComponent(courseLbl))))
                                .addGap(6, 6, 6)
                                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gradingPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fnameLbl)
                                            .addComponent(fnameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(courseIdBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gradingPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lnameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ictLbl)
                    .addComponent(ictTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mathLbl)
                    .addComponent(mathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicsLbl)
                    .addComponent(physicsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bioLbl)
                    .addComponent(bioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chemistryLbl)
                    .addComponent(chemTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(englishLbl)
                    .addComponent(englishTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commerceLbl)
                    .addComponent(commerceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(literatureLbl)
                    .addComponent(literatureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLbl)
                    .addComponent(totalTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgLbl)
                    .addComponent(avgTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankLbl)
                    .addComponent(rankTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(gradingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 470, 450));

        transcriptPanel.setBackground(new java.awt.Color(1, 148, 158));

        transcriptLbl.setBackground(new java.awt.Color(244, 255, 253));
        transcriptLbl.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        transcriptLbl.setForeground(new java.awt.Color(244, 255, 253));
        transcriptLbl.setText("Transcript");

        transcriptArea.setColumns(20);
        transcriptArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        transcriptArea.setRows(5);
        jScrollPane1.setViewportView(transcriptArea);

        javax.swing.GroupLayout transcriptPanelLayout = new javax.swing.GroupLayout(transcriptPanel);
        transcriptPanel.setLayout(transcriptPanelLayout);
        transcriptPanelLayout.setHorizontalGroup(
            transcriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transcriptPanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(transcriptLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transcriptPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        transcriptPanelLayout.setVerticalGroup(
            transcriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transcriptPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(transcriptLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainPanel.add(transcriptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 370, 450));

        jTable1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentId", "CourseId", "Rank", "Average", "Total", "ICT", "Maths", "Physics", "Biology", "Chemistry", "English", "Commerce", "Literature"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        mainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 880, 170));

        deleteBtn.setBackground(new java.awt.Color(237, 37, 78));
        deleteBtn.setForeground(new java.awt.Color(244, 255, 253));
        deleteBtn.setText("Delete");
        deleteBtn.setToolTipText("Delete the record");
        deleteBtn.setFocusable(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        mainPanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4095, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JFrame frame;
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Do you want exit?", "Students Grading System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        JTextField clear = null;
        for (Component c : gradingPanel.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clear = (JTextField) c;
                clear.setText(null);
            }
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        double[] num = new double[8];
        double calTot = 0;

        num[0] = Double.parseDouble(ictTxtField.getText());
        num[1] = Double.parseDouble(mathTxtField.getText());
        num[2] = Double.parseDouble(physicsTxtField.getText());
        num[3] = Double.parseDouble(bioTxtField.getText());
        num[4] = Double.parseDouble(chemTxtField.getText());
        num[5] = Double.parseDouble(englishTxtField.getText());
        num[6] = Double.parseDouble(commerceTxtField.getText());
        num[7] = Double.parseDouble(literatureTxtField.getText());

        // loop through fields and calculate the total
        for (int i = 0; i < num.length; i++) {
            calTot = calTot + num[i];
        }

        // calclulate average
        double calAverage = calTot / num.length;

        String total = String.format("%.0f", calTot);
        totalTxtBx.setText(total);

        String average = String.format("%.0f", calAverage);
        avgTxtBx.setText(average);

        // ranking
        if (Integer.parseInt(total) >= 700) {
            rankTxtBx.setText("1st");
        } else if (Integer.parseInt(total) >= 500) {
            rankTxtBx.setText("2nd upper");
        } else if (Integer.parseInt(total) >= 400) {
            rankTxtBx.setText("2nd lower");
        } else if (Integer.parseInt(total) >= 250) {
            rankTxtBx.setText("3rd");
        } else {
            rankTxtBx.setText("Fail");
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            studentIdTxtBx.getText(),
            courseIdBx.getSelectedItem(),
            rankTxtBx.getText(),
            avgTxtBx.getText(),
            totalTxtBx.getText(),
            ictTxtField.getText(),
            mathTxtField.getText(),
            physicsTxtField.getText(),
            bioTxtField.getText(),
            chemTxtField.getText(),
            englishTxtField.getText(),
            commerceTxtField.getText(),
            literatureTxtField.getText(),});

    }//GEN-LAST:event_calculateBtnActionPerformed

    private void transcriptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcriptBtnActionPerformed
        transcriptArea.append("        Students Grading System\n"
                + "        ========================"
                + "\n\tICT:\t\t\t" + ictTxtField.getText()
                + "\n\tMathematics:\t\t" + mathTxtField.getText()
                + "\n\tPhysics:\t\t" + physicsTxtField.getText()
                + "\n\tBiology:\t\t" + bioTxtField.getText()
                + "\n\tChemistry:\t\t" + chemTxtField.getText()
                + "\n\tEnglish:\t\t" + englishTxtField.getText()
                + "\n\tCommerce:\t\t" + commerceTxtField.getText()
                + "\n\tLiterature:\t\t" + literatureTxtField.getText()
                + "\n        ========================\n"
                + "\n\tTotal:\t\t" + totalTxtBx.getText()
                + "\n\tAverage:\t" + avgTxtBx.getText()
                + "\n\tRank:\t\t" + rankTxtBx.getText());
    }//GEN-LAST:event_transcriptBtnActionPerformed

    private void ictTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ictTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_ictTxtFieldKeyTyped

    private void mathTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_mathTxtFieldKeyTyped

    private void physicsTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_physicsTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_physicsTxtFieldKeyTyped

    private void bioTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bioTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_bioTxtFieldKeyTyped

    private void chemTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_chemTxtFieldKeyTyped

    private void englishTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_englishTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_englishTxtFieldKeyTyped

    private void commerceTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commerceTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_commerceTxtFieldKeyTyped

    private void literatureTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_literatureTxtFieldKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_literatureTxtFieldKeyTyped

    private void studentIdTxtBxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIdTxtBxKeyTyped
        char typed = evt.getKeyChar();
        if (!(Character.isDigit(typed)) || (typed == KeyEvent.VK_BACK_SPACE) || (typed == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_studentIdTxtBxKeyTyped

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data", "Students Grading System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to delete the data from", "Students Grading System", JOptionPane.OK_OPTION);
            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradingCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgLbl;
    private javax.swing.JTextField avgTxtBx;
    private javax.swing.JLabel bioLbl;
    private javax.swing.JTextField bioTxtField;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JTextField chemTxtField;
    private javax.swing.JLabel chemistryLbl;
    private javax.swing.JLabel commerceLbl;
    private javax.swing.JTextField commerceTxtField;
    private javax.swing.JComboBox<String> courseIdBx;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel englishLbl;
    private javax.swing.JTextField englishTxtField;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JTextField fnameTxtBx;
    private javax.swing.JLabel gradesLbl;
    private javax.swing.JPanel gradingPanel;
    private javax.swing.JLabel ictLbl;
    private javax.swing.JTextField ictTxtField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel literatureLbl;
    private javax.swing.JTextField literatureTxtField;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JTextField lnameTxtBx;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mathLbl;
    private javax.swing.JTextField mathTxtField;
    private javax.swing.JLabel physicsLbl;
    private javax.swing.JTextField physicsTxtField;
    private javax.swing.JLabel rankLbl;
    private javax.swing.JTextField rankTxtBx;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel stuIdLbl;
    private javax.swing.JTextField studentIdTxtBx;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField totalTxtBx;
    private javax.swing.JTextArea transcriptArea;
    private javax.swing.JButton transcriptBtn;
    private javax.swing.JLabel transcriptLbl;
    private javax.swing.JPanel transcriptPanel;
    // End of variables declaration//GEN-END:variables
}
